<?php

// see http://stackoverflow.com/questions/2050859
function recurse_copy($src,$dst) { 
    $dir = opendir($src); 
    @mkdir($dst); 
    while(false !== ( $file = readdir($dir)) ) { 
        if (( $file != '.' ) && ( $file != '..' )) { 
            if ( is_dir($src . '/' . $file) ) { 
                recurse_copy($src . '/' . $file,$dst . '/' . $file); 
            } 
            else { 
                copy($src . '/' . $file,$dst . '/' . $file); 
            } 
        } 
    } 
    closedir($dir); 
}

function manage_deploy_commerce_create_product($sku, $title, $price_cents, $type) {
  if (commerce_product_validate_sku_unique($sku, NULL)) {
    $product = new stdClass;
    $product->sku = $sku;
    $product->title = $title;
    $product->type = $type;
    $product->commerce_price = array(
      LANGUAGE_NONE => array(
        array(
          'amount' => $price_cents,
          'currency_code' => 'CAD',
        ),
      ),
    );
    commerce_product_save($product);
  }
}
